### ISSUE TITLE
Bad disk usage calculation

### ISSUE THREAD

**Issue by guiguem** [project8/swarm#14]
From Walter (https://github.com/project8/dragonfly/issues/116)
The disk usage percentage reported to Slack doesn't match that calculated by `df` on a machine, presumably because `Used+Available != Size` and because diopsid only sends the size(?) and used.

Current reporting on zeppelin - 
diopsid
```
a8d0 17:11:16.008 INFO [main] ▶ Alert sent: [/data/warm] All: 938.26 GB Used: 719.31 GB
```
Slack
```
zeppelin:/data/warm -> Free space below threshold (24%); need to monitor!
```
df
```
/dev/sda1       983835532 754249988  179586544  81% /data/warm
```

**Comment by guiguem** [comment]
Need to change fs.Bfree in diopsid to fs.Bavail as available is available to user and is what we are actually interested in...

**Comment by wcpettus** [comment]
just to document this so we never need to re-excavate the rabbit hole:

- `fs.Bsize` = 4096 for claude and zeppelin (4 kB block size)
- `fs.Blocks  * fs.Bsize / 1024` will match "1K-blocks" of `df`
- `fs.Avail * fs.Bsize / 1024` will match "Available" of `df`
- `(fs.Blocks-fs.Bfree) * fs.Bsize / 1024` will match "Used" of `df`
- "Use%" of `df` is rounding up of "Used/(Used+Available)" of `df`

Validated with a modified version of diopside and `df`:
```
010 17:48:46.466 DEBU [DiskUsage] ▶ Bsize:  4096
012 17:48:46.466 DEBU [DiskUsage] ▶ Blocks: 60057984 blocks, 240231936 kB 
013 17:48:46.466 DEBU [DiskUsage] ▶ Bfree:  60042843 blocks, 240171372 kB
014 17:48:46.466 DEBU [DiskUsage] ▶ Bavail: 56986293 blocks, 227945172 kB
015 17:48:46.466 DEBU [DiskUsage] ▶ Used:   15141 blocks, 60564 kB
016 17:48:46.466 INFO [main] ▶ Alert sent: [/data/hot] Used: 60564 KB, Use Fraction: 0.000
017 17:48:46.466 DEBU [DiskUsage] ▶ Bsize:  4096
018 17:48:46.466 DEBU [DiskUsage] ▶ Blocks: 245958883 blocks, 983835532 kB 
01a 17:48:46.466 DEBU [DiskUsage] ▶ Bfree:  245940561 blocks, 983762244 kB
01b 17:48:46.466 DEBU [DiskUsage] ▶ Bavail: 233440811 blocks, 933763244 kB
01c 17:48:46.466 DEBU [DiskUsage] ▶ Used:   18322 blocks, 73288 kB
01d 17:48:46.466 INFO [main] ▶ Alert sent: [/data/warm] Used: 73288 KB, Use Fraction: 0.000
pettus@zeppelin:~/golang$ df
Filesystem      1K-blocks      Used  Available Use% Mounted on
...
/dev/sda1       983835532     73288  933763244   1% /data/warm
/dev/sdb1       240231936     60564  227945172   1% /data/hot
...
```

**Comment by guiguem** [comment]
This is solved now
